### ISSUE TITLE
Issue with induce_incremental ?

### ISSUE THREAD

**Issue by fxs130430** [friguzzi/aleph#9]
Hi professor Riguzzi,
I am trying to run the 'member' example ( incremental learning) and I am not able to see some of the menu options such as overgeneral overspecific etc. I greatly appreciate your help with that.

**Comment by friguzzi** [comment]
Should be fixed by b1716530fd798b1277c121428da69e308ed07464

**Comment by fxs130430** [comment]
I still get the same result. I'm putting the trace of 'mem' example. I hope it helps.

?- induce_incremental.

    Options:
        -> "ok." to accept default example
        -> Enter an example
        -> ctrl-D or "none." to end

    Response [default:none] ?
|: mem(1,[1]).
[sat] [1]
[mem(1,[1])]

[bottom clause]
mem(A,B) :-
   B=[A|C].
[literals] [2]
[saturation time] [0.0]
[reduce]

    Options:
        -> "ok." to accept default example
        -> Enter an example
        -> ctrl-D or "none." to end

    Response [default:mem(1,[1])] ?
|: ok.
[sat] [1]
[mem(1,[1])]

[bottom clause]
mem(A,B) :-
   B=[A|C].
[literals] [2]
[saturation time] [0.0]
[reduce]

    Options:
        -> "ok." to accept default example
        -> Enter an example
        -> ctrl-D or "none." to end

    Response [default:mem(1,[1])] ?
|:

**Comment by friguzzi** [comment]
Have you done
`read_all(mem).`
before running `induce_incremental`?
Please try the sequence of commands in the `typescript` file in the folder `interactive`. It works for me
